import { useState } from "react"; import { useNavigate } from "react-router-dom"; import { Download, Plus, X } from "lucide-react"; import CrudPage,{status} from "../components/CrudPage"; import { useData } from "../context/DataContext"; import { api } from "../services/api"; import "./Certificates.css";
export default function Certificates(){
  const d=useData(),nav=useNavigate(); const [stockOpen,setStockOpen]=useState(false),[stock,setStock]=useState({vcid:"",notes:""}),[stockError,setStockError]=useState("");
  const download=async r=>{window.open(`${api.base}/certificates/${r._id}/pdf`,"_blank")};
  const saveStock=async e=>{e.preventDefault();setStockError("");try{await d.vcidStocksApi.create({vcid:stock.vcid.trim(),status:"Available",notes:stock.notes});setStock({vcid:"",notes:""});setStockOpen(false);}catch(err){setStockError(err.message)}};
  const availableVcids=d.vcidStocks.filter(v=>String(v.status||"Available").toLowerCase()==="available").map(v=>v.vcid).filter(Boolean);
  return <><CrudPage title="Certificates" eyebrow="VERIFICATION RECORDS" description="Create, track, print and download verification certificates without losing expiry dates." resource="certificates" rows={d.certificates} api={d.certificatesApi} onView={r=>nav(`/certificates/${r._id}`)} extraActions={r=><button className="icon-btn" title="Download PDF" onClick={()=>download(r)}><Download size={16}/></button>} headerActions={<button className="btn btn-secondary" onClick={()=>{setStockError("");setStockOpen(true)}}><Plus size={18}/> Add New VCID Stock</button>} fields={[
{name:"certificateNumber",label:"Certificate Number",required:true,placeholder:"VC-000001"},{name:"customerName",label:"Customer",type:"combobox",options:d.customers.map(c=>c.customerName).filter(Boolean),required:true},{name:"vcid",label:"Available VCID",type:"select",options:availableVcids,required:true},{name:"companyName",label:"Company / Shop"},{name:"scaleId",label:"Scale ID",required:true},{name:"scaleType",label:"Scale Type"},{name:"capacity",label:"Capacity"},{name:"make",label:"Make"},{name:"model",label:"Model"},{name:"serialNumber",label:"Serial Number"},{name:"verificationDate",label:"Verification Date",type:"date",required:true},{name:"expiryDate",label:"Expiry Date",type:"date",required:true},{name:"amount",label:"Certificate Amount",type:"number"},{name:"status",label:"Status",type:"select",options:["Active","Expiring Soon","Expired","Cancelled"]},{name:"notes",label:"Notes",type:"textarea",wide:true}]} columns={[
{key:"certificateNumber",label:"Certificate"},{key:"customerName",label:"Customer"},{key:"vcid",label:"VCID"},{key:"scaleId",label:"Scale ID"},{key:"expiryDate",label:"Expiry"},{key:"status",label:"Status",render:r=>status(r.status)}]}/>
  {stockOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setStockOpen(false)}><div className="modal"><div className="modal-head"><div><div className="eyebrow">NEW VCID STOCK</div><h2>Add New VCID Stock</h2></div><button className="icon-btn" onClick={()=>setStockOpen(false)}><X size={18}/></button></div><form onSubmit={saveStock}><div className="form-grid"><label className="field"><span>VCID Number</span><input value={stock.vcid} onChange={e=>setStock({...stock,vcid:e.target.value})} required placeholder="VC-000001"/></label><label className="field"><span>Status</span><input value="Available" readOnly/></label><label className="field wide"><span>Notes</span><textarea rows="3" value={stock.notes} onChange={e=>setStock({...stock,notes:e.target.value})}/></label></div>{stockError&&<div className="alert">{stockError}</div>}<div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setStockOpen(false)}>Cancel</button><button className="btn btn-primary">Save VCID Stock</button></div></form></div></div>}
  </>
}
